### ISSUE TITLE
File upload?

### ISSUE THREAD

**Issue by jesperordrup** [usefulio/forms#38]
Hi! 
Nice and clean form implementation. Thanks!!

Any advise on how to add file upload ?

best, 

Jesper

**Comment by cwohlman** [comment]
Hi @jesperordrup,

For file upload I'd recommend you write a template to handle file upload, either using a service like filepicker.io, or html5 http://www.html5rocks.com/en/tutorials/file/dndfiles/.

Here's some (partial) code I wrote to integrate filepicker with useful forms:

``` html
<template name="formFieldFilePicker">
    {{#each photos}}
      <img src="{{thumbnail.url}}">
    {{/each}}
    <br>
    <input
      disabled={{converting}}
      type="filepicker"
      name="{{this.name}}"
      data-fp-drag-text="Or drop photo here"
      data-fp-drag-class="pane-photopicker"
      data-fp-extensions=".png,.jpeg,.jpg,.JPG,.PNG,.JPEG"
      data-fp-container="modal" 
      data-fp-store-location="S3"
      data-fp-store-access="public"
    >
</template>
```

``` js

Template.formFieldFilePicker.helpers({
  photos: function (){
    return this.form.value(this.name) || [];
  }
  , converting: function () {
    return Template.instance().converting.get();
  }
});

Template.formFieldFilePicker.events({
  'change [type="filepicker"]': function(e, tmpl){
    var self = this;
    var files = e.originalEvent.fpfiles ? e.originalEvent.fpfiles : [e.originalEvent.fpfile];
    var path = '/varieties/' + (this.variety ? this.variety.name : '');
    _.each(files, function(file){
      if(file){
        tmpl.converting.set(true);
        App.resizeAndWatermark(file, path, function(err, result){
          file.thumbnail = result.thumbnail;
          file.large = result.large;
          file._id = Random.id();
          var photos = self.form.value(self.name) || [];
          photos.push(file);
          var changes = { };
          changes[self.name] = photos;
          $(e.currentTarget).trigger('propertyChange', changes)
          tmpl.converting.set(false);
        });
      }
    });
    e.stopPropagation();
    e.stopImmediatePropagation();
    e.preventDefault();
  }
  , 'click img': function (e, tmpl) {
    var self = Template.parentData().form;
    var photo = this;
    var confirmed = confirm('Would you like to remove this photo?');
    if(confirmed){
      var photos = self.form.value(self.name) || [];
      photos = _.filter(photos, function (a) {
        return a._id !== photo._id;
      });
      self.form.set(self.name, photos);
    }
  }
});
```

You'll definitely have to modify this code to fit your own use case, for example:
1. Note that I use `this.name` and `this.form` you'll need to be sure that you pass those values into the template when you use it
2. This doesn't include the code necessary to setup filepicker
3. This upload is customized for photos/images, you might be uploading some other kind of file.
4. We call `App.resizeAndWatermark` which is some custom code we wrote for customizing uploaded images, you'll need to remove that call, and just add the file directly.

Hopefully this should get you started on the right track for how to build a custom component. You'll probably want to ask implementation specific questions on stack overflow, especially if you decide to try and implement the html5 file upload instead of using filepicker.
